modLoader = "javafml"
loaderVersion = "[47,)"
license = "All rights reserved"

[[mods]]
modId = "faunaandorchestra"
version = "${mod_version}"
displayName = "Fauna & Orchestra"
authors = "Owlest"
description = "Add a little bit of music to your world! Whether you only want a little bit more of life (Mantises, Red Pandas, Baby Penguins...) or create your perfect orchestra, this is the perfect mod!"

# --- MIXINS ---
[[mixins]]
config = "mixins.faunaandorchestra.json"

# --- DEPENDENCIAS ---

# 1. Minecraft
[[dependencies.faunaandorchestra]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.2)"
ordering = "NONE"
side = "BOTH"

# 2. Forge
[[dependencies.faunaandorchestra]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.faunaandorchestra]]
modId = "geckolib"
mandatory = true
versionRange = "[4.4.5,)"
ordering = "NONE"
side = "BOTH"

# 4. Patchouli (OBLIGATORIA)
[[dependencies.faunaandorchestra]]
modId = "patchouli"
mandatory = true
versionRange = "[1.20.1-84.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.faunaandorchestra]]
modId = "jei"
mandatory = false
versionRange = "[15.20.0.127,)"
ordering = "NONE"
side = "CLIENT"