modLoader = "javafml"
loaderVersion = "[47,)"
license = "All rights reserved"

[[mods]]
modId = "faunaandorchestra"
version = "${mod_version}"
displayName = "Fauna & Orchestra"
authors = "Owlest"
description = "A magical exploration mod where nature meets symphony! Tame unique musical fauna to build your orchestra and gain powerful buffs. Craft costumes with the Sewing Machine, send letters via Mailbirds, collect music droplets, and dive into arcane sound magic to restore harmony against the Great Composer."

# --- MIXINS ---
[[mixins]]
config = "mixins.faunaandorchestra.json"

# --- DEPENDENCIES ---

[[dependencies.faunaandorchestra]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.faunaandorchestra]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.faunaandorchestra]]
modId = "geckolib"
mandatory = true
versionRange = "[4.4.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.faunaandorchestra]]
modId = "patchouli"
mandatory = true
versionRange = "[1.20.1-84.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.faunaandorchestra]]
modId = "jei"
mandatory = false
versionRange = "[15.20.0.112,)"
ordering = "NONE"
side = "CLIENT"