package net.migueel26.faunaandorchestra.item;

import net.migueel26.faunaandorchestra.FaunaAndOrchestra;
import net.migueel26.faunaandorchestra.block.ModBlocks;
import net.migueel26.faunaandorchestra.util.RecipesUtil;
import net.migueel26.faunaandorchestra.util.VesselUtil;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.ItemStack;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.RegistryObject;

public class ModCreativeModeTabs {
    public static final DeferredRegister<CreativeModeTab> CREATIVE_MODE_TAB =
            DeferredRegister.create(Registries.CREATIVE_MODE_TAB, FaunaAndOrchestra.MOD_ID);

    public static final RegistryObject<CreativeModeTab> FAUNA_AND_ORCHESTRA = CREATIVE_MODE_TAB.register("fauna_and_orchestra_tab",
            () -> CreativeModeTab.builder().icon(() -> new ItemStack(ModItems.ICON.get()))
                    .title(Component.literal("Fauna & Orchestra"))
                    .displayItems((itemDisplayParameters, output) -> {
                        output.accept(ModItems.VIOLIN.get());
                        output.accept(ModItems.FLUTE.get());
                        output.accept(ModItems.KEYTAR.get());
                        output.accept(ModItems.DOUBLE_BASS.get());
                        output.accept(ModItems.SAXOPHONE.get());
                        output.accept(ModItems.OBOE.get());
                        output.accept(ModItems.CELLO.get());
                        output.accept(ModItems.DRUM.get());
                        output.accept(ModItems.PAN_FLUTE.get());
                        output.accept(ModItems.PAN_FLUTE_CREATIVE.get());
                        output.accept(ModItems.BATON.get());
                        output.accept(ModItems.LEGENDARY_BATON.get());
                        output.accept(ModItems.BRIEFCASE.get());
                        output.accept(ModItems.SOUND_SENSOR.get());
                        output.accept(ModItems.FROG_FLUTE.get());
                        output.accept(ModItems.BUTTERFLY_NET.get());
                        output.accept(ModItems.BUTTERFLY_SPAWN_EGG.get());
                        output.accept(ModItems.MANTIS_SPAWN_EGG.get());
                        output.accept(ModItems.PENGUIN_SPAWN_EGG.get());
                        output.accept(ModItems.EMPEROR_PENGUIN_SPAWN_EGG.get());
                        output.accept(ModItems.RED_PANDA_SPAWN_EGG.get());
                        output.accept(ModItems.MACAW_SPAWN_EGG.get());
                        output.accept(ModItems.BEAVER_SPAWN_EGG.get());
                        output.accept(ModItems.LEMUR_SPAWN_EGG.get());
                        output.accept(ModItems.MADAME_BUTTERFLY_SPAWN_EGG.get());
                        output.accept(ModItems.SEA_LION_SPAWN_EGG.get());
                        output.accept(ModItems.QUIRKY_FROG_SPAWN_EGG.get());
                        output.accept(ModItems.WORKER_KOALA_SPAWN_EGG.get());
                        output.accept(ModItems.WANDERING_KOALA_SPAWN_EGG.get());
                        output.accept(ModItems.BUTLER_KOALA_SPAWN_EGG.get());
                        output.accept(ModItems.LIVING_MUSIC_SPAWN_EGG.get());
                        output.accept(ModItems.SPROUTLING_SPAWN_EGG.get());
                        output.accept(ModItems.RINGTAILS_SPAWN_EGG.get());
                        output.accept(ModItems.JAZZY_DAMMYS_SPAWN_EGG.get());
                        output.accept(ModItems.WISE_TREE_SPAWN_EGG.get());
                        output.accept(ModItems.THE_GREAT_COMPOSER_SPAWN_EGG.get());
                        output.accept(ModBlocks.MANTIS_EGG.get());
                        output.accept(ModItems.MANTIS_CLAW.get());
                        output.accept(ModItems.MANTIS_DAGGER.get());
                        output.accept(ModItems.MANTIS_FOOD.get());
                        output.accept(ModItems.WORM.get());
                        output.accept(ModItems.INSECT.get());
                        output.accept(ModItems.COTTON_PLANT_SEEDS.get());
                        output.accept(ModItems.COTTON.get());
                        output.accept(ModItems.ARCTIC_FUMES.get());
                        output.accept(ModBlocks.HANGING_JAR.get());
                        output.accept(ModBlocks.JAR_RACK.get());
                        output.accept(ModBlocks.CATCHWEED.get());
                        output.accept(ModItems.NATURE_FUMES.get());
                        output.accept(ModItems.BADGRASS_MEAL.get());
                        output.accept(ModItems.FLORA_FORTA.get());
                        output.accept(ModItems.EVERFRUIT.get());
                        output.accept(ModItems.FLOATING_BLOSSOM.get());
                        output.accept(ModItems.FLORAL_BOOTS.get());
                        output.accept(ModItems.FLORAL_FUMES.get());
                        output.accept(ModItems.PERFUMED_BAMBOO.get());
                        output.accept(ModItems.SHARP_BAMBOO.get());
                        output.accept(ModItems.BAMBOO_TRAP_ITEM.get());
                        output.accept(ModItems.TAIYAKI.get());
                        output.accept(ModItems.PENGUIN_FEATHER.get());
                        output.accept(ModItems.FLUFFY_BOOTS.get());
                        output.accept(ModItems.REALLY_GOOD_STICK.get());
                        output.accept(ModItems.BEAVER_STATUE_ITEM.get());
                        output.accept(ModItems.SEEDY_APPLE.get());
                        output.accept(ModItems.MACAW_FEATHER.get());
                        output.accept(ModItems.WRITING_INK.get());
                        output.accept(ModBlocks.LETTER_AND_QUILL.get());
                        output.accept(ModItems.MAILBOX_ITEM.get());
                        output.accept(ModItems.BACH_AIR_SHEET_MUSIC.get());
                        output.accept(ModItems.GREENSLEEVES_SHEET_MUSIC.get());
                        output.accept(ModItems.BLUES_SHEET_MUSIC.get());
                        output.accept(ModItems.JAZZY_FUR_ELISE_SHEET_MUSIC.get());
                        output.accept(ModItems.DANCE_OF_THE_LITTLE_SWANS.get());
                        output.accept(ModItems.LA_BAMBA_SHEET_MUSIC.get());
                        output.accept(ModItems.SAINTS_SHEET_MUSIC.get());
                        output.accept(ModItems.OH_SUSANNA_SHEET_MUSIC.get());
                        output.accept(ModItems.THE_ENTERTAINER_SHEET_MUSIC.get());
                        output.accept(ModItems.RESURRECTION_SONG.get());
                        output.accept(ModItems.SHEET_FRAGMENTS.get());
                        output.accept(ModItems.WHISTLE.get());
                        output.accept(ModItems.MUSIC_BOTTLE.get());
                        output.accept(ModItems.MUSICAL_INK.get());
                        output.accept(ModItems.EXTRACT_OF_LIVING_MUSIC.get());
                        output.accept(ModItems.MUSIC_JAM.get());
                        output.accept(ModItems.BOOGIE_BOMB.get());
                        output.accept(ModItems.SONIC_FUMES.get());
                        output.accept(ModItems.STEELSONIC_INGOT.get());
                        output.accept(ModItems.AMPLIFIER_CRYSTAL.get());
                        output.accept(ModItems.VOICE_VESSEL.get());
                        output.accept(ModItems.GINKGO_BILOBA.get());
                        output.accept(ModItems.BIOSONIC_INGOT.get());
                        output.accept(ModItems.BIOSONIC_DIRK.get());
                        output.accept(ModBlocks.FLORA_ENHANCER.get());
                        output.accept(ModItems.WANDERING_NOTE.get());
                        output.accept(ModItems.BOOGIE_FRUIT.get());
                        output.accept(ModItems.SINGING_SEED.get());
                        output.accept(ModItems.GLOVE.get());
                        output.accept(ModItems.FORTUNE_COOKIE.get());
                        output.accept(ModBlocks.TIP_CASE.get());
                        output.accept(ModBlocks.LISTENER.get());
                        output.accept(ModBlocks.LISTENER_CONTAINER.get());
                        output.accept(ModItems.MELOMANCY_CAULDRON_ITEM.get());
                        output.accept(ModItems.MOTHER_STATUE_ITEM.get());
                        output.accept(ModBlocks.VOICE_CHAMBER.get());
                        output.accept(ModBlocks.ALTAR_OF_THE_PAN_FLUTE.get());
                        output.accept(ModBlocks.ALTAR_OF_THE_BUTTERFLIES.get());
                        output.accept(ModBlocks.ALTAR.get());
                        output.accept(ModBlocks.COMPOSER_GRAVESTONE.get());
                        output.accept(ModBlocks.GRAVESTONE.get());
                        output.accept(ModItems.THE_GREAT_HEAD_ITEM.get());
                        output.accept(ModItems.TRANSMUTED_VOICE.get());
                        output.accept(ModItems.DISCORD_ESSENCE.get());
                        output.accept(ModItems.ACTIVATOR_CLEF.get());
                        output.accept(ModItems.PETALS_OF_DEATH.get());
                        output.accept(ModBlocks.DISCORDED_FLOWER.get());
                        output.accept(ModItems.DISCORD_BOMB.get());
                        output.accept(ModItems.DISCORD_NUCLEI_ITEM.get());
                        output.accept(ModBlocks.CRAWLING_DISCORD.get());
                        output.accept(ModBlocks.DISCORD_BLOCK.get());
                        output.accept(ModBlocks.DAM_BLOCK.get());
                        output.accept(ModBlocks.GINGKO_BILOBA_LEAVES.get());
                        output.accept(ModBlocks.GINGKO_BILOBA_SAPLING.get());
                        output.accept(ModItems.FRUIT_OF_LIFE.get());
                        output.accept(ModItems.OFFERING.get());
                        output.accept(ModItems.BUSINESS_CARD.get());
                        output.accept(ModItems.SEWING_KIT.get());
                        output.accept(ModItems.MELOMANCY_KIT.get());
                        output.accept(ModItems.FARMING_KIT.get());
                        output.accept(ModItems.SEWING_MACHINE_ITEM.get());
                        output.accept(ModItems.PROP_CASE.get());
                        output.accept(ModItems.WHITE_TUXEDO.get());
                        output.accept(ModItems.TUXEDO.get());
                        output.accept(ModItems.TAILCOAT.get());
                        output.accept(ModItems.BASEBALL_JACKET.get());
                        output.accept(ModItems.SANTA_COSTUME.get());
                        output.accept(ModItems.RIGHT_MONOCLE.get());
                        output.accept(ModItems.LEFT_MONOCLE.get());
                        output.accept(ModItems.FAKE_MOUSTACHE.get());
                        output.accept(ModItems.ROSE.get());
                        output.accept(ModItems.IMAGINAL_DISK.get());
                        output.accept(ModItems.MASK_OF_THE_ENLIGHTENED.get());
                        output.accept(ModItems.TOP_HAT.get());
                        output.accept(ModItems.SANTA_HAT.get());
                        output.accept(ModItems.BASEBALL_CAP.get());
                        output.accept(ModItems.PROPELLER_HAT.get());
                        output.accept(ModItems.GOLDEN_TINT.get());
                        output.accept(ModItems.SILVER_TINT.get());
                        output.accept(ModItems.COLORFUL_TINT.get());
                        output.accept(ModItems.UNLIT_MASK.get());
                        output.acceptAll(RecipesUtil.getAllRecipeItems());
                        output.acceptAll(VesselUtil.getAllVoiceItems());
                        output.accept(ModItems.UNLOCKER.get());
                    }).build());


    public static void register(IEventBus eventBus) {
        CREATIVE_MODE_TAB.register(eventBus);
    }
}
