package net.migueel26.faunaandorchestra.item;

import net.migueel26.faunaandorchestra.FaunaAndOrchestra;
import net.migueel26.faunaandorchestra.block.ModBlocks;
import net.migueel26.faunaandorchestra.util.VesselUtil;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.ItemStack;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.neoforge.registries.DeferredRegister;

import java.util.function.Supplier;

public class ModCreativeModeTabs {
    public static final DeferredRegister<CreativeModeTab> CREATIVE_MODE_TAB =
            DeferredRegister.create(Registries.CREATIVE_MODE_TAB, FaunaAndOrchestra.MOD_ID);

    public static final Supplier<CreativeModeTab> FAUNA_AND_ORCHESTRA = CREATIVE_MODE_TAB.register("fauna_and_orchestra",
            () -> CreativeModeTab.builder().icon(() -> new ItemStack(ModItems.ICON.get()))
                    .title(Component.literal("Fauna & Orchestra"))
                    .displayItems((itemDisplayParameters, output) -> {
                        output.accept(ModItems.VIOLIN);
                        output.accept(ModItems.FLUTE);
                        output.accept(ModItems.KEYTAR);
                        output.accept(ModItems.DOUBLE_BASS);
                        output.accept(ModItems.SAXOPHONE);
                        output.accept(ModItems.OBOE);
                        output.accept(ModItems.CELLO);
                        output.accept(ModItems.DRUM);
                        output.accept(ModItems.PAN_FLUTE);
                        output.accept(ModItems.PAN_FLUTE_CREATIVE);
                        output.accept(ModItems.BATON);
                        output.accept(ModItems.LEGENDARY_BATON);
                        output.accept(ModItems.BRIEFCASE);
                        output.accept(ModItems.SOUND_SENSOR);
                        output.accept(ModItems.FROG_FLUTE);
                        output.accept(ModItems.BUTTERFLY_NET);
                        output.accept(ModItems.BUTTERFLY_SPAWN_EGG);
                        output.accept(ModItems.MANTIS_SPAWN_EGG);
                        output.accept(ModItems.PENGUIN_SPAWN_EGG);
                        output.accept(ModItems.EMPEROR_PENGUIN_SPAWN_EGG);
                        output.accept(ModItems.RED_PANDA_SPAWN_EGG);
                        output.accept(ModItems.MACAW_SPAWN_EGG);
                        output.accept(ModItems.BEAVER_SPAWN_EGG);
                        output.accept(ModItems.LEMUR_SPAWN_EGG);
                        output.accept(ModItems.MADAME_BUTTERFLY_SPAWN_EGG);
                        output.accept(ModItems.SEA_LION_SPAWN_EGG);
                        output.accept(ModItems.QUIRKY_FROG_SPAWN_EGG);
                        output.accept(ModItems.WORKER_KOALA_SPAWN_EGG);
                        output.accept(ModItems.WANDERING_KOALA_SPAWN_EGG);
                        output.accept(ModItems.BUTLER_KOALA_SPAWN_EGG);
                        output.accept(ModItems.SPROUTLING_SPAWN_EGG);
                        output.accept(ModItems.RINGTAILS_SPAWN_EGG);
                        output.accept(ModItems.JAZZY_DAMMYS_SPAWN_EGG);
                        output.accept(ModItems.WISE_TREE_SPAWN_EGG);
                        output.accept(ModItems.THE_GREAT_COMPOSER_SPAWN_EGG);
                        output.accept(ModBlocks.MANTIS_EGG);
                        output.accept(ModItems.MANTIS_CLAW);
                        output.accept(ModItems.MANTIS_DAGGER);
                        output.accept(ModItems.MANTIS_FOOD);
                        output.accept(ModItems.WORM);
                        output.accept(ModItems.INSECT);
                        output.accept(ModBlocks.HANGING_JAR);
                        output.accept(ModBlocks.JAR_RACK);
                        output.accept(ModBlocks.CATCHWEED);
                        output.accept(ModItems.NATURE_FUMES);
                        output.accept(ModItems.BADGRASS_MEAL);
                        output.accept(ModItems.EVERFRUIT);
                        output.accept(ModItems.FLOATING_BLOSSOM);
                        output.accept(ModItems.PERFUMED_BAMBOO);
                        output.accept(ModItems.SHARP_BAMBOO);
                        output.accept(ModItems.BAMBOO_TRAP_ITEM);
                        output.accept(ModItems.TAIYAKI);
                        output.accept(ModItems.PENGUIN_FEATHER);
                        output.accept(ModItems.FLUFFY_BOOTS);
                        output.accept(ModItems.BEAVER_STATUE_ITEM);
                        output.accept(ModItems.MACAW_FEATHER);
                        output.accept(ModItems.WRITING_INK);
                        output.accept(ModBlocks.LETTER_AND_QUILL);
                        output.accept(ModItems.MAILBOX_ITEM);
                        output.accept(ModItems.BACH_AIR_SHEET_MUSIC);
                        output.accept(ModItems.GREENSLEEVES_SHEET_MUSIC);
                        output.accept(ModItems.BLUES_SHEET_MUSIC);
                        output.accept(ModItems.JAZZY_FUR_ELISE_SHEET_MUSIC);
                        output.accept(ModItems.DANCE_OF_THE_LITTLE_SWANS);
                        output.accept(ModItems.LA_BAMBA_SHEET_MUSIC);
                        output.accept(ModItems.SAINTS_SHEET_MUSIC);
                        output.accept(ModItems.RESURRECTION_SONG);
                        output.accept(ModItems.SHEET_FRAGMENTS);
                        output.accept(ModItems.WHISTLE);
                        output.accept(ModItems.MUSIC_BOTTLE);
                        output.accept(ModItems.MUSICAL_INK);
                        output.accept(ModItems.EXTRACT_OF_LIVING_MUSIC);
                        output.accept(ModItems.BOOGIE_BOMB);
                        output.accept(ModItems.STEELSONIC_INGOT);
                        output.accept(ModItems.AMPLIFIER_CRYSTAL);
                        output.accept(ModItems.VOICE_VESSEL);
                        output.accept(ModItems.GINKGO_BILOBA);
                        output.accept(ModItems.WANDERING_NOTE);
                        output.accept(ModItems.BOOGIE_FRUIT);
                        output.accept(ModItems.SINGING_SEED);
                        output.accept(ModItems.GLOVE);
                        output.accept(ModItems.FORTUNE_COOKIE);
                        output.accept(ModBlocks.TIP_CASE);
                        output.accept(ModBlocks.LISTENER);
                        output.accept(ModBlocks.LISTENER_CONTAINER);
                        output.accept(ModItems.MELOMANCY_CAULDRON_ITEM);
                        output.accept(ModItems.MOTHER_STATUE_ITEM);
                        output.accept(ModBlocks.VOICE_CHAMBER);
                        output.accept(ModBlocks.ALTAR_OF_THE_PAN_FLUTE);
                        output.accept(ModBlocks.ALTAR_OF_THE_BUTTERFLIES);
                        output.accept(ModBlocks.ALTAR);
                        output.accept(ModBlocks.COMPOSER_GRAVESTONE);
                        output.accept(ModBlocks.GRAVESTONE);
                        output.accept(ModItems.THE_GREAT_HEAD_ITEM);
                        output.accept(ModItems.TRANSMUTED_VOICE);
                        output.accept(ModItems.DISCORD_ESSENCE);
                        output.accept(ModItems.ACTIVATOR_CLEF);
                        output.accept(ModItems.PETALS_OF_DEATH);
                        output.accept(ModBlocks.DISCORDED_FLOWER);
                        output.accept(ModItems.DISCORD_BOMB);
                        output.accept(ModItems.DISCORD_NUCLEI_ITEM);
                        output.accept(ModBlocks.CRAWLING_DISCORD);
                        output.accept(ModBlocks.DISCORD_BLOCK);
                        output.accept(ModBlocks.DAM_BLOCK);
                        output.accept(ModBlocks.GINGKO_BILOBA_LEAVES);
                        output.accept(ModBlocks.GINGKO_BILOBA_SAPLING);
                        output.accept(ModItems.FRUIT_OF_LIFE);
                        output.accept(ModItems.OFFERING);
                        output.accept(ModItems.BUSINESS_CARD);
                        output.accept(ModItems.SEWING_KIT);
                        output.accept(ModItems.MELOMANCY_KIT);
                        output.accept(ModItems.FARMING_KIT);
                        output.accept(ModItems.SEWING_MACHINE_ITEM);
                        output.accept(ModItems.PROP_CASE);
                        output.accept(ModItems.TUXEDO);
                        output.accept(ModItems.TAILCOAT);
                        output.accept(ModItems.BASEBALL_JACKET);
                        output.accept(ModItems.SANTA_COSTUME);
                        output.accept(ModItems.RIGHT_MONOCLE);
                        output.accept(ModItems.LEFT_MONOCLE);
                        output.accept(ModItems.FAKE_MOUSTACHE);
                        output.accept(ModItems.ROSE);
                        output.accept(ModItems.IMAGINAL_DISK);
                        output.accept(ModItems.MASK_OF_THE_ENLIGHTENED);
                        output.accept(ModItems.TOP_HAT);
                        output.accept(ModItems.SANTA_HAT);
                        output.accept(ModItems.BASEBALL_CAP);
                        output.accept(ModItems.PROPELLER_HAT);
                        output.accept(ModItems.GOLDEN_TINT);
                        output.accept(ModItems.SILVER_TINT);
                        output.accept(ModItems.COLORFUL_TINT);
                        output.acceptAll(VesselUtil.getAllVoiceItems());
                        output.accept(ModItems.UNLOCKER);
                    }).build());


    public static void register(IEventBus eventBus) {
        CREATIVE_MODE_TAB.register(eventBus);
    }
}
